import {compare} from './compare'
import {RecSimplify} from './rec'

/**
 * Creates an array of specified length, with each element generated by `at`.
 */
export function arrayMake<Item>(length: number, at: (index: number) => Item) {
	const result = Array(length)
	for (let i = 0; i < length; i++) {
		result[i] = at(i)
	}
	return result
}

/**
 * Adds every item to the returned object's array property which name is generated by `groupFor`.
 */
export function arrayGroup<Item, Group extends string>(
	arr: readonly Item[],
	getGroup: (item: Item, index: number) => Group
) {
	let result = {} as Record<Group, Item[]>
	arr.forEach((item, index) => {
		(result[getGroup(item, index)] ??= []).push(item)
	})
	return result as RecSimplify<typeof result>
}

/**
 * Cleaner syntax for `Promise.all(arr.map(async item => doSomethingAsync(item))`.
 */
export function arrayMapAsync<Item, Result>(
	arr: readonly Item[],
	fn: (item: Item, index: number) => Promise<Result> | Result
) {
	return Promise.all(arr.map(fn)) as Promise<Awaited<Result>[]>
}

/**
 * Skips repeated array items.
 */
export function arrayDedupe<Item>(arr: Item[]) {
	return [...new Set(arr)]
}

export function arrayReplace<
	Item,
	Target extends Item,
	Replacement extends Item
>(
	arr: Item[],
	target: Target,
	replacement: Replacement
) {
	return arr.map(item => {
		return compare(item, target) ? replacement : item
	}) as Array<Exclude<Item, Target> | Replacement>
}
