import {compare} from './compare'
import {RecSimplify} from './rec'

/**
 * Creates an array of specified length, with each element generated by `at`.
 */
export function arrayMake<Item>(
	length: number,
	at: (index: number) => Item
) {
	return Array.from({length}, (_, index) => at(index))
}

/**
 * Adds every item to the returned object's array property which name is generated by `groupFor`.
 */
export function arrayGroup<Item, Group extends string>(
	arr: readonly Item[],
	groupFor: (item: Item, index: number) => Group
) {
	const result = {} as Record<Group, Item[]>

	arr.forEach((item, index) => {
		(result[groupFor(item, index)] ??= []).push(item)
	})

	return result as RecSimplify<typeof result>
}

/**
 * Cleaner syntax for `Promise.all(arr.map(async item => doSomethingAsync(item))`.
 */
export function arrayMapAsync<I, O>(
	arr: I[],
	mapper: (item: I, index: number) => Promise<O> | O
): Promise<Awaited<O>[]> {
	return Promise.all(arr.map(mapper))
}

/**
 * Skips repeated array items.
 */
export function arrayDedupe<Item>(arr: Item[]) {
	return [...new Set(arr)]
}

export function arrayReplace<Item, What extends Item, With extends Item>(
	arr: Item[],
	what: What,
	// "with" is occupied by a deprecated keyword
	vith: With
) {
	return (
		arr.map(item => compare(item, what) ? vith : item)
	) as Array<Exclude<Item, What> | With>
}
