import {RecSimplify} from './rec'

/**
 * Creates an array of specified length, with each element generated by `at`.
 */
export function arrayMake<Item>(
	length: number,
	at: (index: number) => Item
) {
	return Array.from({length}, (_, index) => at(index))
}

/**
 * Adds every item to the returned object's array property which name is generated by `groupFor`.
 */
export function arrayGroup<Item, Group extends string>(
	items: readonly Item[],
	groupFor: (item: Item, index: number) => Group
) {
	const result = {} as Record<Group, Item[]>

	items.forEach((item, index) => {
		(result[groupFor(item, index)] ??= []).push(item)
	})

	return result as RecSimplify<typeof result>
}

/**
 * Cleaner syntax for `Promise.all(arr.map(async item => doSomethingAsync(item))`.
 */
export function arrayMapAsync<I, O>(
	arr: I[],
	mapper: (item: I, index: number) => Promise<O> | O
): Promise<Awaited<O>[]> {
	return Promise.all(arr.map(mapper))
}

/**
 * Skips repeated array items.
 */
export function arrayDedupe<T>(arr: T[]) {
	return [...new Set(arr)]
}
